// <auto-generated />
using System;
using JobSearch.Application.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobSearch.Application.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529010000_AddScheduledJobRunStatus")]
    partial class AddScheduledJobRunStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("JobSearch.Domain.Entities.CandidateProfileSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResumeText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CandidateProfile");
                });


            modelBuilder.Entity("JobSearch.Domain.Entities.ScheduledJobRunStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResult")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastRunCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastRunSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastRunStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NextExpectedRunAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScheduledJobRunStatuses", t =>
                        {
                            t.HasCheckConstraint("CK_ScheduledJobRunStatuses_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("JobSearch.Domain.Entities.JobOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateApplied")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateFound")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FitScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneratedRecruiterMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemoteType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"Source\" IS NOT NULL AND \"ExternalId\" IS NOT NULL");

                    b.HasIndex("Source", "Url")
                        .IsUnique()
                        .HasFilter("\"Source\" IS NOT NULL AND \"ExternalId\" IS NULL AND \"Url\" IS NOT NULL");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobSearch.Domain.Entities.JobOpportunity", b =>
                {
                    b.OwnsOne("JobSearch.Domain.Entities.FitScoreResult", "FitScoreResult", b1 =>
                        {
                            b1.Property<Guid>("JobOpportunityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Concerns")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("FitScore")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("MatchingSkills")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("MissingSkills")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RecommendedAction")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JobOpportunityId");

                            b1.ToTable("Jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobOpportunityId");
                        });

                    b.Navigation("FitScoreResult");
                });
#pragma warning restore 612, 618
        }
    }
}
